### ISSUE TITLE
supporting data request

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangoLEARN#1]
Hi,

would it be possible to extend the supported data with a file, not only holding the lineage description, but also the most common countries and date of first detection? By now I take the data from the www-page (i did not find a better way). But looks like the lineage descriptions in the supportig data folder are more up to date, than the wepbage (e.g. B.1.1.7), or at least different.

Best,
Anke

**Comment by aineniamh** [comment]
Just seeing this issue now! Actually that information already exists here: https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.json
Hope it's helpful!
