### ISSUE TITLE
Would you add the VUI B.1.617 please?

### ISSUE THREAD

**Issue by xzhub** [cov-lineages/pangoLEARN#10]
Not sure if there is a rule that only VOCs will be considered and VUI won't be added, but if there is no such rule, would you please consider adding the new strain reported in India?

**Comment by aineniamh** [comment]
Hi, we have both B.1.617 and its sublineages included in the pangoLEARN model.

**Comment by xzhub** [comment]
Thanks for that information! Where can I confirm if a lineage is included or not? I am looking at https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineage_recall_report.csv, but did not find B.1.617

**Comment by xzhub** [comment]
I believe I should watch this file for the lineage updating: https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt
hope this can help someone else.
