### ISSUE TITLE
Problem with lineage P.1.2

### ISSUE THREAD

**Issue by aplamarca** [cov-lineages/pangoLEARN#14]
Hello everyone!

PangoLearn is not assigning sequences as P.1.2. I have commented about this on the lineage designation issue of P.1.2, and Christopher Ruis has kindly told me that it would (possibly) fixed by yesterday, 25th. The last update of PangoLearn has not solved it and I would like to know if this problem is still being worked on. 

Thank you in advance!

**Comment by aplamarca** [comment]
Hello everyone!

In the last update this matter was solved. Thank you!

**Comment by aineniamh** [comment]
Ah thank you, meant to respond to this! I knew we had an update in the works that should have resolved it. Thanks for your patience!
