### ISSUE TITLE
pangoLEARN python code causes flake8 issue

### ISSUE THREAD

**Issue by pvanheus** [cov-lineages/pangoLEARN#15]
This line - https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/__init__.py#L3 - in the `__init__.py` is flagged by flake8 as a problem because of the lack of space around the `=`. This causes a problem with tools using `pangoLEARN` and also being validated with `flake8`.

**Comment by aineniamh** [comment]
Ah thanks, I've fixed that in the master and will note it for future releases!
