### ISSUE TITLE
pangoLEARN update

### ISSUE THREAD

**Issue by santoshe1** [cov-lineages/pangoLEARN#18]
Hello Team,

I had a question on whether we could just update the pangoLEARN version without updating pangolin. I had some scripts written which uses the variants_of_concern output and the new version of pangolin has removed them. So, I was wondering if only the pangoLEARN model could be updated frequently?

**Comment by aineniamh** [comment]
I think this is similar to the discussion on this issue here: https://github.com/cov-lineages/pangolin/issues/229

**Comment by santoshe1** [comment]
Thank you

**Comment by santoshe1** [comment]
![PangoLearn_Error](https://user-images.githubusercontent.com/35063856/121657780-c2bb2980-cab1-11eb-8a98-f1b84e0d5392.png)

Hello, 

I am getting the above error if I run pangolin v2.4.2 with the latest pangoLEARN version. The last compatible version of pangoLEARN is 2021-05-19. Could this issue be looked into?

Thank you

**Comment by aineniamh** [comment]
Ahh, it's because we don't provide the lineages.metadata.csv file anymore. I can create a dummy file that will find it and that should resolve the issue.

**Comment by aineniamh** [comment]
I think this should be resolved now, so will close. If not can reopen.
