### ISSUE TITLE
2021-01-11 release

### ISSUE THREAD

**Issue by andersgs** [cov-lineages/pangoLEARN#2]
Hello.

The commit bb0ca4ef27 suggests a 2021-01-11 release, but none was made. Just wondering if this is on purpose.

Thank you.

Anders.

**Comment by aineniamh** [comment]
It's still being trained unfortunately, our usual server wasn't available at the time and the training has taken far longer on this different system (@emilyscher's laptop) than we'd anticipated. We'll push and tag the release as soon as the training finishes!

**Comment by andersgs** [comment]
Thank you for the response. Good luck with the training. Maybe some dedicated cloud VM would be appropriate. Could we hit up Amazon or Google or Microsoft for help?
