### ISSUE TITLE
B.1.1.397 scoring metrics

### ISSUE THREAD

**Issue by victormaricato** [cov-lineages/pangoLEARN#20]
Are the metrics for `B.1.1.397` available anywhere?

Tried to find it in the [report](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineage_recall_report.csv#L245), however, I couldn't.

Plus, the sample where `B.1.1.397` was found in my dataset is actually assigned as P.1 in the Usher model and is definitely within other P.1's in their Phylogenetic Tree, which is why I am looking for the pangoLEARN metrics on this specific variant.

**Comment by rmcolq** [comment]
That file is not currently maintained, so will not feature any of the more recent lineages. This is an old issue now, and I suspect  any misclassification has been resolved by the latest pangoLEARN data release. The pangoLEARN/data/decision_tree_rules.zip is the file which has information in about decisions made within pangoLEARN for each lineage.
