### ISSUE TITLE
The `__version__` is not updated for 2021-04-23

### ISSUE THREAD

**Issue by philiptzou** [cov-lineages/pangoLEARN#5]
Just want to let you know, the `__version__` variable of tag 2021-04-23 is still 2021-04-21.

https://github.com/cov-lineages/pangoLEARN/blob/7a6423480e417bfc08ae7e82ee7417072b62f218/pangoLEARN/__init__.py#L2

**Comment by aineniamh** [comment]
Ah thank you! I've fixed that now.
