### ISSUE TITLE
Pangolearn Update

### ISSUE THREAD

**Issue by santoshe1** [cov-lineages/pangoLEARN#53]
Hello Angie,

Could you let me know when would the pangolearn be updated to pango-designation release v1.2.100 to detect B.1.1.529 lineage?

Best,
Santosh

**Comment by AngieHinrichs** [comment]
Hi Santosh,

I expect there will be a new release of pangoLEARN some time in the next few days with both the pangoLEARN trained model and usher lineageTree.pb updated to pango-designation v1.2.101.  In the meantime, if you run `pangolin --update` then you will get the latest version of the constellations repository (v0.0.24), which includes a constellations file for B.1.1.529: https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cB.1.1.529.json.  Then pangolin, using scorpio and constellations, will be able to identify B.1.1.529 sequences even without an update to pangoLEARN or usher.  

If you run `pangolin --update`, and still pangolin/scorpio/constellations does not assign B.1.1.529 to a sequence that has B.1.1.529 mutations, then please let us know.  

Angie

**Comment by santoshe1** [comment]
Thank you for the response Angie :) I shall let you know if I have any issues in detecting B.1.1.529
