### ISSUE TITLE
show pango-designation version when using pangolin/pangoLEARN

### ISSUE THREAD

**Issue by TYMichaelsen** [cov-lineages/pangoLEARN#7]
Hi cov-lineages team, 
Maybe i'm missing something obvious, but it seems odd to me that the version of pango-designation is not explicitly stated for the current version of pangolin/pangoLEARN I'm using? It would be very handy if it could, then I don't have to dig around in the github pages trying to match up release date of pango-designations and pangoLEARN. Also I might make a mistake! :) 

Thanks for brilliant software,
Thomas

**Comment by aineniamh** [comment]
Hi @TYMichaelsen, I've written code into our training pipeline today that should include the designation version too. The next data release will have this information in!

**Comment by TYMichaelsen** [comment]
Hi @aineniamh, awesome! thanks
