### ISSUE TITLE
Dependency quokka to run the training pipeline

### ISSUE THREAD

**Issue by fischer-hub** [cov-lineages/pangoLEARN#74]
Hi! Such a nice project!
I'm trying to retrain the pangoLEARN model to use on more fragmented sequences using the train-pipeline from this repo (`training_runner.sh`). I found all the other dependencies like pango-designation and pangolin, however I still get a missing dependency:

```
python: can't open file '/home/recombination/quokka/quokka/getRelevantLocationsObject.py': [Errno 2] No such file or directory
```

I just can't seem to find the mentioned quokka repository or the `getRelevantLocationsObject.py` file anywhere..

Thanks in advance!

**Comment by aineniamh** [comment]
Hi both, the quokka repository can be installed with 
```
pip install git+https://github.com/cov-lineages/quokka.git
```
I don't think that this should be a dependency and all training scripts should be part of the pangoLEARN repository. We're getting ready for a release rather soon, and I've been away so am just catching up on where the pipeline is at the moment. I'll get back to you soon about this when I know more!
