### ISSUE TITLE
detect the recombinant lineage (pango-designation v1.2.133)

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pangoLEARN#75]
I understand that pangoLEARN is generally updated biweekly.
Would the next update of pangolearn be able to detect the recombinant lineage XD, XE and XF?
Thank you.

**Comment by aineniamh** [comment]
Hi @alantsangmb, we're in the process of preparing the next data release (having some memory issues that we're just sorting out at the moment). That will be trained on v1.2.133, so should be possible to have these recombinants assigned. 

A big caveat is we're not 100% sure how well pangolin is going to do with assigning recombinants. Early tests I did on lineage XA showed mixed results. The pangoLEARN method can be pretty sensitive to missing data and conflicting signals in the training set. The UShER method, which will be the default as of pangolin 4.0, will place the sequence in the most parsimonious context so if the recombinant is in the tree it should place it correctly, although we need to investigate this further. 

So in answer to your question, theoretically yes but basically we're going to do some more testing to see how well these methods fare for recombinant assignment- it's next on our list of things to address!

**Comment by alantsangmb** [comment]
Thank you so much for the work and reply.
I understand that it is challenging to study the recombination dynamic events.
