### ISSUE TITLE
Lineage recall report is not updated

### ISSUE THREAD

**Issue by aretchless** [cov-lineages/pangoLEARN#8]
Hello. It looks like the [lineage_recall_report](https://github.com/cov-lineages/pangoLEARN/blob/master/pangoLEARN/data/lineage_recall_report.csv) in this project is not being updated with everything else. The current version is 3 months old and does not include Variants of Concern such as P.1.

I'm interested in this report because I'm working on a study evaluating disease severity for VOCs, and it would help to understand how reliable the sequence assignment is for each lineage.

Thanks for providing this critical tool for understanding the pandemic!

**Comment by aineniamh** [comment]
Hi @aretchless, thanks for flagging this. It's a known issue with a bug in the script to generate this. @emilyscher is on the case though!
