### ISSUE TITLE
pangoLEARN seems to detect only a third of XEs

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pangoLEARN#81]
UKHSA says it's got ~1200 XEs in the UK. CovSpectrum agrees.

Yet pangoLEARN calls only about 37% correctly as XE.

<img width="2520" alt="image" src="https://user-images.githubusercontent.com/25161793/162496961-2eeaf769-f091-4fa4-85b8-5ba6a693cd01.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nucMutations=C3241T%2CT5386G%2CC12880T%2CC14599T%2CA29510C&

**Comment by aineniamh** [comment]
Thanks for flagging!

**Comment by alantsangmb** [comment]
Most of them are overridden by Scorpio call
