### ISSUE TITLE
pangolin version in __init__.py is not updated

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangoLEARN#9]
Hi,

pangolin --update
pangolin already latest release (v2.3.8)
pangoLEARN updated to 2021-04-23

however, in the __init__.py we have still  2021-04-21 and in the pangolin resultsfile as well...

I find only pangoLEARN-2021_04_21.dist-info in my miniconda3 directory.

Greets

**Comment by replikation** [comment]
* can confirm this error

**Comment by aineniamh** [comment]
Resolved in latest version!
